### ISSUE TITLE
Embed settings: embed type "double" problem

### ISSUE THREAD

**Issue by noahzgard** [ElvUI-WotLK/ElvUI_AddOnSkins#79] opened 2018-02-09 23:06 UTC
I'm tryin' to setup Skada and Omen window in right chat window. When using Embed type double with 2 skada windows it works as intedent. But when i use Skada and Omen windows, both windows use left part.

**Comment by Loaal** [comment] 2019-08-28 23:33
Can't reproduce. For me Skada and Omen embed options works fine. Closing issue because it's old and maybe already fixed in major update of main. If you'll encounter same problem please open new issue.

**Closed by Loaal** 2019-08-28 23:33 UTC
